# Generated by Django 5.2 on 2025-11-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_saletransaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the entire bulk pack', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units in a bulk pack'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(default='units', help_text='e.g., pieces, kg, liters, packs', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('bundle', 'Bundle Deal')], max_length=20)),
                ('minimum_quantity', models.PositiveIntegerField()),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='core.product')),
            ],
        ),
    ]
