# Generated by Django 5.2 on 2026-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_bulk_price_product_bulk_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the entire bulk pack', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='change_given',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
