# Generated by Django 5.2 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Store', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Modern Point of Sale', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for your business!', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
