# Generated by Django 5.2 on 2026-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='plan_tier',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('BUSINESS', 'Business')], default='BUSINESS', max_length=10),
        ),
    ]
